version: '3.3'
services:
  db-payment:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'alurafood-pagamento'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'application'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'application'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'application' 
      MYSQL_ROOT_HOST: 'localhost'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  db-order:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'alurafood-pedidos'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'application'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'application'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'application' 
      MYSQL_ROOT_HOST: 'localhost'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql-order    
      
# Names our volume
volumes:
  my-db:
